name: Linter
permissions:
  pull-requests: read
  checks: write

on:
    push:
      branches:
        - "master"
        - "renovate/**"
    pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    # python-lint
    - name: Install the latest version of ruff
      uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
      with:
        version: "latest"
        args: "format --check --diff"
    - name: Run Ruff linter
      run: |
        # check the formatted codes
        ruff check --select I --fix
        ruff format
        # run the linters
        ruff check .
    # Dockerfile lint
    - name: hadolint
      uses: reviewdog/action-hadolint@1b2cfa6ba72072ad35158d7ff3aa49bbdc03506d # v1.51.0
      with:
        hadolint_ignore: DL3007 SC2114
        reporter: github-check

    # misspell
    - name: misspell
      uses: reviewdog/action-misspell@d6429416b12b09b4e2768307d53bef58d172e962 # v1.27.0
      with:
        locale: "US"
        reporter: github-check
    # AutoCorrect
    - name: AutoCorrect
      uses: huacnlee/autocorrect-action@bf91ab3904c2908dd8e71312a8a83ed1eb632997 # main
    - name: Report ReviewDog
      if: failure()
      uses: huacnlee/autocorrect-action@bf91ab3904c2908dd8e71312a8a83ed1eb632997 # main
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        reviewdog: true
