name: Publish to PyPI
permissions: {}

on:
  push:
    branches: [ "master" ]
    paths:
    - '.github/workflows/pypi-publish.yml'
    - 'pdm.lock'
    - 'pyproject.toml'
  workflow_dispatch:

jobs:
  pypi-publish:
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: pdm-project/setup-pdm@544d7237314ee09c256785bd360f6b30add38b37 # v4.6
      - name: Publish package distributions to PyPI
        run: pdm publish --repository pypi
